### PR TITLE
Feature/add gem gas dataset

### PR DESCRIPTION
**Pull request by Tomkourou**
Closes # (if applicable).

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Other

## Checklist

- [x] I have added a note to release notes `doc/release_notes.rst`.
- [x] I have used `pre-commit run --all` to lint/format/check my contribution
- [x] I have documented the effects of my code changes in the documentation `doc/`.
- [ ] I have adjusted the docstrings in the code appropriately.

### CODE REVIEW

**Comment by FabianHofmann** [comment]
Hey @Tomkourou, sorry for being a bit slow. I'll try to have a look at the PR next week!

**Comment by Tomkourou** [comment]
> Hi @FabianHofmann all good, thanks for getting back to me! the GEM datasets don't currently have a direct link to download. You have to make a request via their website and a link (which breaks I just checked) with the file is sent to you. Its nevertheless a Creative Commons CC BY-NC-SA 4.0 License (see [here](https://globalenergymonitor.org/projects/global-gas-plant-tracker/download-data/) , so I would suggest to simply reupload it somewhere. Do you have a suggestion on the best place to store the csv?  

PS: I also see a list of target countries in the config.yaml. Should this be updated now we are talking about global datasets?

**Comment by Tomkourou** [comment]
I think we're good to go @FabianHofmann !

**Comment by FabianHofmann** [comment]
Awesome, so you managed to get a url? For the countries I don't think we have to include the other countries, now. This can happen at a later point

**Pull request merged**
